# -*- coding: utf-8 -*-
"""pib_pais.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1915JnJPlEAREqs73vinwGqxM-1lmKUNK
"""

#lembrar de upar o arquivo csv na pasta 'Files' ao lado 
#e renomeá-lo para 'PIBs.csv'. Link abaixo:

# https://docs.google.com/spreadsheets/d/17ph-3NHpGV3GH0R2_eErd-23K8gmpcGexQTxLDcjbDg/edit?usp=sharing

import pandas as pd
import matplotlib.pyplot as plt
 
def exibir_PIB_pais():
  #informar dados
  pais = input('Informe o nome de um país: ')
  ano = input('Informe um ano entre 2013 e 2020: ')
 
  #abrir data frame
  df = pd.read_csv('PIBs.csv')
 
  #incluir todos os países/anos do data frame numa lista(para fazer verificação)
  lista_paises = []
  lista_ano = []
  lista_ano = df.columns.values.tolist()
  lista_ano.remove('País')
 
  for paises in df['País'].values:
    lista_paises.append(paises)
 
  if pais in lista_paises and ano in lista_ano:
    x = df.loc[df['País'] == pais, ano].values[0]  #localiza o valor solicitado
    print(f'\nPIB {pais} em {ano}: US${x} trilhões.\n')
  elif pais not in lista_paises and ano not in lista_ano:
    print('País e ano não disponíveis. Tente novamente')
    exibir_PIB_pais()
  elif pais not in lista_paises:
    print('País não disponível. Tente novamente')
    exibir_PIB_pais()
  else:
    print('Ano não disponível. Tente novamente')
    exibir_PIB_pais()
 
def exibir_variacao():
  pib_a = []
  pib_b = []
  lista_paises = []
 
  for paises in df['País'].values:
      lista_paises.append(paises)
 
  for paises in lista_paises:
    pib = df.loc[df['País'] == paises, '2013'].values[0]  #localiza o valor solicitado
    pib_a.append(pib)
 
  for paises in lista_paises:
    pib2 = df.loc[df['País'] == paises, '2020'].values[0]  #localiza o valor solicitado
    pib_b.append(pib2)
 
  for i in range(15):
    variacao = ((pib_b[i] / pib_a[i]) - 1) * 100
    txt = "Variação de {valor:.2f}"
    print(f'{lista_paises[i].ljust(20)}' + txt.format(valor = variacao) + '% entre 2013 e 2020.')

def exibir_variacao():
  pib_a = []
  pib_b = []
  lista_paises = []

  #abrir data frame
  df = pd.read_csv('PIBs.csv')

  for paises in df['País'].values:
      lista_paises.append(paises)

  for paises in lista_paises:
    pib = df.loc[df['País'] == paises, '2013'].values[0]  #localiza o valor solicitado
    pib_a.append(pib)

  for paises in lista_paises:
    pib2 = df.loc[df['País'] == paises, '2020'].values[0]  #localiza o valor solicitado
    pib_b.append(pib2)

  for i in range(15):
    variacao = ((pib_b[i] / pib_a[i]) - 1) * 100
    txt = "Variação de {valor:.2f}"
    print(f'{lista_paises[i].ljust(20)}' + txt.format(valor = variacao) + '% entre 2013 e 2020.')

def exibir_grafico():
  #informar dados
  pais = input('Informe o nome de um país: ')

  df = pd.read_csv('PIBs.csv')

  lista_paises = []
  for paises in df['País'].values:
      lista_paises.append(paises)

  if pais in lista_paises:
    lista_ano = []
    lista_ano = df.columns.values.tolist()
    lista_ano.remove('País')
    df.loc[df['País'] == pais].values.tolist()

    lista_pib = []
    lista_pib = df.loc[df['País'] == pais].values.tolist()
    lista_pib2 = lista_pib[0]
    lista_pib2.remove(pais)

    plt.plot(lista_ano, lista_pib2)
    plt.xlabel('Ano')
    plt.ylabel('PIB')
    plt.title(f'{pais} - Evolução do PIB entre 2013 e 2020')
    plt.show()
  else:
    print('Esse país não consta na lista. Tente novamente')
    exibir_grafico()

def opcoes():
  print('Digite 1 para exibir o PIB de um país em um determinado ano')
  print('Digite 2 para exibir a variação do PIB de todos os países entre 2013 e 2020')
  print('Digite 3 para exibir o gráfico de evolução do PIB de um país')
  print('==============================================================\n')
  opcao = input('Informe sua a opção desejada: ')

  if opcao == '1':
    exibir_PIB_pais()
  elif opcao == '2':
    exibir_variacao()
  elif opcao == '3':
    exibir_grafico()
  else:
    print('Opção inválida. Tente novamente')
    opcoes()

opcoes()